---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  releaseName: bazarr
  interval: 5m
  chart:
    spec:
      chart: bazarr
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/bazarr
      tag: v0.9.0.2-ls89
    env:
      TZ: "Europe/London"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "bazarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "bazarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: local-path
        size: 2Gi
      movies:
        enabled: true
        existingClaim: jbhdd-movies-pvc
        mountPath: /movies
      tv:
        enabled: true
        existingClaim: jbhdd-tv-pvc
        mountPath: /tv
