apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: metallb-system
spec:
  interval: 1h
  targetNamespace: metallb-system
  path: ./kubernetes/coffee-shop-2/apps/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: metallb-system
spec:
  interval: 1h
  targetNamespace: metallb-system
  path: ./kubernetes/coffee-shop-2/apps/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
  dependsOn:
    - name: app
