apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 5m
  releaseName: loki-stack
  chart:
    spec:
      chart: loki-stack
      version: 2.4.1
      sourceRef:
        name: grafana
        namespace: monitoring
        kind: HelmRepository
  values:
    loki:
      enabled: true
      persistence:
        storageClassName: "local-storage"
        enabled: true
        size: 10Gi
    promtail:
      enabled: true
    grafana:
      enabled: true
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          enabled: false
      server:
        persistentVolume:
          enabled: false


