---

- name: kubeconfig | copy config file to $PWD
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "./kubeconfig"
    flat: true
  when:
  - k3s_control_node is defined
  - k3s_control_node

- name: kubeconfig | update kubeconfig with the right IPv4 address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "./kubeconfig"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ k3s_registration_domain }}:6443'
