---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jbhdd-music
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: jbhdd-music-pvc
    namespace: media
  nfs:
    path: /mnt/jbhdd/music
    server: 192.168.4.2
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jbhdd-music-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
