---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-data
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/photoprism
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cappuccino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-data
  namespace: photoprism
spec:
  storageClassName: local-path
  volumeName: photoprism-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-originals
spec:
  storageClassName: local-path
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/jbhdd/photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cappuccino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals
  namespace: photoprism
spec:
  storageClassName: local-path
  volumeName: photoprism-originals
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
