---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-upload
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/imageupload
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cappuccino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imageupload
  namespace: photoprism
spec:
  storageClassName: local-path
  volumeName: image-upload
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
