apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: photoprism
spec:
  encryptedData:
    auth: AgANw7zI2iaCjkcg8TuB5heuVjr3+93/y4FdK0Q0NOAMoi4D+Fl6cB+IAyHRJet9nK1oDxd/N7uv42e3w9aETkpCy42L61EkAT4+bM5hWyJSY+ULtj9xmoaEXs3hXdukQZP+oL6D2RoOrF8Vxf57iWKa0Cmjq5ipsPFBqZhB+mxykGxrIG3sMuc1kfzFQYHpmhuJvQyS/Oucl/fANeWb7ZWXmWTnDZYynnwVfRk2Nwtbk1uPahyXtrUYL24gUQdX3mvnpdSWjpAJ4DSVbyYuqboInoUth9eRoWuhpgVWYCV+2FLKD3MW0N29y0y60HbPX4YA6UaO6oBEN+Xq2ajup1cVloFFxWPU+4SCOQSODKfXpyRyYhdizXRGfzi2PW5o2BSe5dvtal4MUewfaNpMQnGZzSMRcY+QvTbTvuP2ooQ/pXL9A4MGrizehDO5Z8AfR5g3oaguECl98KUZwFV2syZRuOFOtjn672GJibmBCt2NYu06Ce0KvvcCagl3/22wVQJTKuWR8A4uXO7hw9FBeXoi5NjF4DeZsuaHG19m6Kwe0viaKlZZSB87e9s3iz2gbo0pYD4Mrr6KPjTsEoLOGVlejxr5Ros+87NUWV1h1LPuxUQ6Xeg+j/1vRGtKAAox6gtnRWPWm/YP/To8IMDcOwNAc8EL/SymSUHdxQZ2UO1EU7GNK4VEkpD6652ZKQ17NxXZ5N1lm6gAS7bczscjtIc3MXpx6w8gmpGHhHHW64SpVLXCD8os5jVJseM6SbeeX/w=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: photoprism

