---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  releaseName: metallb
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 6.3.5
      sourceRef:
        name: bitnami
        namespace: flux-system
        kind: HelmRepository
  values:
    installCrds: true
    controller:
      image:
        repository: bitnami/metallb-controller
        tag: 0.14.5-debian-12-r7
      psp:
        create: false
    speaker:
      image:
        repository: bitnami/metallb-speaker
        tag: 0.14.5-debian-12-r7
      psp:
        create: false
