---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: home
spec:
  interval: 5m
  releaseName: immich
  chart:
    spec:
      # renovate: registryUrl=https://immich-app.github.io/immich-charts
      chart: immich
      version: 0.7.0
      sourceRef:
        name: immich
        kind: HelmRepository
        namespace: flux-system
  values:
    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: v1.108.0
    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent
      ingress:
        main:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
            external-dns/is-public: "true"
            external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
            hajimari.io/enable: "true"
            hajimari.io/icon: "camera"
          hosts:
            - host: "immich.${SECRET_DOMAIN}"
              paths:
                - path: "/"
          tls:
            - hosts:
                - "immich.${SECRET_DOMAIN}"
      persistence:
        external:
          enabled: true
          existingClaim: immich-external-photos-pvc
          readOnly: true
    redis:
      enabled: true
    postgresql:
      enabled: true
    immich:
      persistence:
        library:
          existingClaim: immich-photos-pvc
