---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/server/ansible"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubernetes/coffee-shop-2/kubeconfig"

includes:
  ansible: .taskfiles/ansible.yml
  flux: .taskfiles/flux.yml
  sops: .taskfiles/sops.yml
  nextcloud: .taskfiles/nextcloud.yml
  db: .taskfiles/db.yml
  bootstrap: .taskfiles/bootstrap.yml

tasks:
  kubeconfig:
    desc: Remotely fetch kubeconfig from k3s
    vars:
      cluster: '{{.cluster | default "coffee-shop-2"}}'
    cmds:
      - rsync --verbose --progress --partial --rsync-path="sudo rsync" debian@192.168.4.5:/etc/rancher/k3s/k3s.yaml {{.KUBECONFIG}}
      - '{{if eq OS "linux"}}sed -i{{else}}sed -i ""{{end}} "s/127.0.0.1/192.168.4.5/g" {{.KUBECONFIG}}'
      - '{{if eq OS "linux"}}sed -i{{else}}sed -i ""{{end}} "s/default/{{.cluster}}/g" {{.KUBECONFIG}}'
      - chmod go-r {{.KUBECONFIG}}
    silent: true

  default: task -l
