---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/server/ansible"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  ansible: .taskfiles/ansible.yml
  flux: .taskfiles/flux.yml
  sops: .taskfiles/sops.yml
  nextcloud: .taskfiles/nextcloud.yml
  db: .taskfiles/db.yml

tasks:
  kubeconfig:
    desc: Remotely fetch kubeconfig from k3s
    cmds:
      - rsync --verbose --progress --partial --rsync-path="sudo rsync" ubuntu@192.168.4.3:/etc/rancher/k3s/k3s.yaml ./kubeconfig
      - '{{if eq OS "linux"}}sed -i{{else}}sed -i ""{{end}} "s/127.0.0.1/192.168.4.3/g" ./kubeconfig'
      - '{{if eq OS "linux"}}sed -i{{else}}sed -i ""{{end}} "s/default/coffee-shop/g" ./kubeconfig'
      - chmod go-r kubeconfig
    silent: true
