apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media-management
spec:
  interval: 5m
  releaseName: radarr
  chart:
    spec:
      chart: radarr
      version: 15.0.3
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v3.2.2.5080
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
        - host: radarr.jonnobrow.co.uk
          paths:
          - path: /
        tls:
        - hosts:
          - radarr.jonnobrow.co.uk
          secretName: radarr-tls-cert
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        mountPath: /media
        existingClaim: radarr-media
        accessMode: ReadWriteMany
      downloads:
        enabled: true
        mountPath: /downloads
        existingClaim: radarr-downloads
        accessMode: ReadWriteMany

