apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cert-manager
      version: v1.15.2
      sourceRef:
        kind: HelmRepository
        namespace: cert-manager
        name: cert-manager
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    crds:
      enabled: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query"
