---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: development
spec:
  interval: 5m
  releaseName: gitea
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts
      chart: gitea
      version: 5.0.0
      sourceRef:
        name: gitea
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: gitea/gitea
      tag: 1.15.10
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/enable: "true"
        hajimari.io/icon: "git"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
      hosts:
        - host: "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "git.${SECRET_DOMAIN}"
    gitea:
      admin:
        username: "${SECRET_GITEA_USERNAME}"
        password: "${SECRET_GITEA_PASSWORD}"
        email: "${SECRET_GITEA_EMAIL}"
      config:
        APP_NAME: "jonnobrow's gitea"
        RUN_MODE: prod
        repository:
          ROOT: /data/git/gitea-repositories
          PREFERRED_LICENSES: GPL-3.0-or-later,Apache-2.0,X11
          ENABLE_PUSH_CREATE_USER: true
          DEFAULT_BRANCH: main
        service:
          DISABLE_REGISTRATION: true
        security:
          PASSWORD_CHECK_PWN: true
        picture:
          DISABLE_GRAVATAR: true
          ENABLE_FEDERATED_AVATAR: true
    postgresql:
      image:
        tag: 13.1.0
      volumePermissions:
        enabled: true
      psp:
        create: true
      rbac:
        create: true
