---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  releaseName: jellyfin
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: jellyfin
      version: 9.4.2
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.8.1
    env:
      TZ: "Europe/London"
      JELLYFIN_PublishedServerUrl: "jellyfin.${SECRET_DOMAIN}"
      JELLYFIN_CACHE_DIR: "/config/cache"
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "jellyfish"
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - "jellyfin.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc
      music:
        enabled: true
        existingClaim: jbhdd-music-pvc
      shows:
        enabled: true
        existingClaim: jbhdd-tv-pvc
      movies:
        enabled: true
        existingClaim: jbhdd-movies-pvc
    resources:
      requests:
        memory: 2048Mi
      limits:
        memory: 3072Mi
