---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: home
spec:
  interval: 5m
  releaseName: hass
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    persistence:
      config:
        enabled: true
        existingClaim: hass-config-pvc
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.11.2
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.${SECRET_DOMAIN}"
