---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  releaseName: frigate
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: home-assistant
      version: 13.0.1
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.4.0
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cog"
        hosts:
          - host: "home-assistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "home-assistant.${SECRET_DOMAIN}"
