---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - local-path-provisioner.yaml
  - nextcloud.yaml
  - photoprism.yaml
  - sealed-secrets.yaml
