---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 10m
  url: https://jvalskis.github.io/mealie-helm/
  timeout: 3m
