---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: development
spec:
  interval: 5m
  releaseName: drone
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        name: drone
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: drone/drone
      tag: 1.9.0
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/enable: "true"
        hajimari.io/icon: "drone"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
      hosts:
        - host: "ci.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "ci.${SECRET_DOMAIN}"
    env:
      # Drone Server Setup
      DRONE_SERVER_HOST: "ci.${SECRET_DOMAIN}"
      DRONE_SERVER_PROTO: https
      DRONE_RPC_SECRET: "${SECRET_DRONE_RPC_SECRET}"
      # Github Credentials
      DRONE_GITHUB_CLIENT_ID: "${SECRET_DRONE_GITHUB_CLIENT_ID}"
      DRONE_GITHUB_CLIENT_SECRET: "${SECRET_DRONE_GITHUB_CLIENT_SECRET}"
      DRONE_USER_CREATE: "username:jonnobrow,admin:true"
