apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-storage
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: local-path-storage
      interval: 1m
