---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: home
spec:
  interval: 5m
  releaseName: mealie
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: mealie
      version: 5.0.0
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    env:
      ALLOW_SIGNUP: "False"
    image:
      repository: hkotel/mealie
      tag: frontend-v1.0.0beta-2
    hostname: mealie
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "food"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
        hosts:
          - host: "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "mealie.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: mealie-data-pvc
        mountPath: /app/data
        readOnly: false
    api:
      image:
        repository: hkotel/mealie
        tag: api-v1.0.0beta-2
      env:
        PUID: 1001
        PGID: 1001
        DEFAULT_EMAIL: "${SECRET_MEALIE_EMAIL}"
        DEFAULT_PASSWORD: "${SECRET_MEALIE_PASSWORD}"
        BASE_URL: "https://mealie.${SECRET_DOMAIN}"
        API_DOCS: "False"
        SMTP_HOST: "${SECRET_SMTP_HOST}"
        SMTP_USER: "${SECRET_SMTP_USERNAME}"
        SMTP_PASSWORD: "${SECRET_SMTP_PASSWORD}"
        SMTP_FROM_EMAIL: "${SECRET_MEALIE_EMAIL}"
        ALLOW_SIGNUP: "False"
      volumeMounts:
        - name: data
          mountPath: /app/data
