---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nextcloud-data-pvc
    namespace: nextcloud
  nfs:
    path: /mnt/jbhdd/data/nextcloud
    server: 192.168.4.2
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  storageClassName: nfs
  volumeName: nextcloud-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
