---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-scans
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nextcloud-scans-pvc
    namespace: nextcloud
  nfs:
    path: /mnt/jbhdd/scans
    server: 192.168.4.4
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-scans-pvc
  namespace: nextcloud
spec:
  storageClassName: nfs
  volumeName: nextcloud-scans
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
