---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: cert-manager
  path: ./kubernetes/coffee-shop-2/apps/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: cert-manager
  path: ./kubernetes/coffee-shop-2/apps/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
  dependsOn:
    - name: cert-manager-app
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: cert-manager
  path: ./kubernetes/coffee-shop-2/apps/cert-manager/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
  dependsOn:
    - name: cert-manager-app
    - name: cert-manager-issuers
  wait: true
