apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAnQLPj+TVKhBxvum8XnKQL0AxgE1tMcOGi4L1Exmy/gDs0v9LOziPcYFViAryGfpAUy6OlMv26UXVjkyo55kVS/FPFllkPyMGNZ4m7ASypU+wEtsx4VacMYeaIqGaGRxIXDw/Fn1KeHFGmtQ+awPw6gfzaOGMNM7AbI3zswu7F5/v+ShT4O87v/P+f+whMDc3b1eUrK1Z/5r5/jEC0HCQ44KYC5+N0c5YbKls/OQq8jXD3ZnVJYi2TjZOKenb/3y+oNeRz5snYGi82K297Fhf85yxe7oXpoaDeC/+Fl+qbVk0571rIjF6GVuEtqWGOMuJmtb2s11tAPwj/RqOrYWJvdng2ydlXTvrDsQtV+WYGEnXH79YSbztotqC/GYZP908wBuTCE/gQlv6/LznndMP8mupIk4f0ZJLH1yWdyrlvex0ndds76LRA4aCtxuqm92Q3MoQi/istMZBjkCNOdGARlW/3el2EMu/vBYQLragxBShLwJyzdpm99WJs78pKRfL5WCITAsZkNwLQWzuz7NXur63rcrEVDuL4C7LT7uvdRiUSfzovoDu4q96KuQn8lCkkDc/zxJCiBr5JfNJahg9qrdJYVSLoGQm4lD1l73Mew8KEqRspgrdSgK7661Us2FiuuQRINqMSfA0wvpWby+BJUbeK1b7XTv9m06xs9lkK9EUPkkvdb7qkQkp1Xz8LGY4PjxQJtg8Q5t2QgOO9uaP40lF8ViQyl78+GBpjDFyH6/xpRDYhCbD+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

