---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: "${SECRET_CLOUDFLARE_EMAIL}"
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
