# yamllint disable
---
apiVersion: v1
data:
    cloudflare_api_key: ENC[AES256_GCM,data:96pRFOYGMXgRb0O0hpy8j8R541P/X8M6RojucbNfLm7CY9HUlY/0KxXQOdVN6bjY7UqlyQ==,iv:cbphH6eqe+qjjG+31HozguTs+no86k8IV0rrREDgZVg=,tag:P4/m5sqZLZ0sEptOQ/Tttg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-api-key
    namespace: networking
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-03T17:01:45Z"
    mac: ENC[AES256_GCM,data:2PBbXqqvhX/qLMs8W7f+8voYwZKn8PLVLJxVKM9Y2NmIdX71KN+IvjRTulqth4XyxjZyXNBT5J8ITLmlzZKwDWX1+XDcO78VyQ+cU4vsMj8t1rGpwBHGnjmCPM1WitIA5pInnFPO8o7ODrAEpXQadmm2Y3BppsTDwBea0KVbCCk=,iv:jMquFTBJuUpTnveMwZOZJPgGjILzfaRzLzMpaWhPxkQ=,tag:g4aHMQL/p6sR/OQpQoRC7g==,type:str]
    pgp:
        - created_at: "2021-10-03T17:01:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzqujJzjVu3QAQ/+LzGSyHVZaYpkMLNxgwxi5vmqE0KOHVUnVoroR0VNHUwG
            kUfdv7NuVehIxTf5E3G1VTiZjhjdFrtcnAyCBn+l4egh017tMJpvR/Ly+zTTqUal
            gYn0+zs7GtNaKYmoMt1WmLPZp625Hb/pHgDMqeEgiWF3++9+HoRSbESgDR+dhujq
            IXTh86R/r0GC95UpoSLPxBGLh8Ekvu4Oe5FWvXeUZUC+yj53UjMoP9rLILQ/Lgoh
            NOiDuJK5SJurPHHphkrKRVzFMJCfAqXn9bWBjGw/NfZZnPFH5950Ch/enzCWRFG/
            /mZdEaPl+H/cxhGFp9Gyoz1bWl9JVtgzKTK+A4zX+rc29RsM0wZwrIZ23JKtfCnF
            voPXug01GYYNaJ168JTK/DQzfJDyEXqyHdePx/lQxozpMWriTGk5Yemj0xnCg0TQ
            2OvGq3CDE5WKBwaleSdb4UDXp4ZTmfc70jvZowNlrFzTiQylGsYntsFo7oDz5Yrf
            dEXqHL7gqGAz6tTg4a6HoMOqRj1jueu6tMrOR1LljhcEAxEGIbd0RakwgD6E6ldb
            3HVgtqRLqf8+Om20fblVF7lJ1w+QuTkYW5CYJBKFzzJJx62YAdm25priLDNgH23q
            jvg32ZieWLvOLX3WU2sEFQLE95YOASQ4zpVplFoCI+BE3XPgYkvmj8pr/cCQjIzS
            XgEPjrdIlcvDi6Op6HhwoeQvPwdlDH8cETgR21ncwP12ug0lWtfd/FTL6Y1Wklqs
            gN1qL+pc5rqkCDoi+J+QNi06YIV9pWoSF9UyQ29jLAxvMWSe4fnlxeeu6kbWAl8=
            =snCo
            -----END PGP MESSAGE-----
          fp: EEC9902152C0690384D8A104D86E27E8B691FAA1
        - created_at: "2021-10-03T17:01:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7ASNUo6AKEMAQ//aBkNHIyNn3Yq8YvWFw+HQ8UJ7AiClW4IHirDCaUplFcL
            9GBEDnOGGdjwioA+Vr6DPYGVpcD0o4ut+P+zYCgL4Jg7O8pABaF3f+B8Rup/FD/d
            5eLuzyU2BdJNcVCRqG30BNy6iqNXqk01m4buUtBQRikJSWviOSG5wpYhtreIStAY
            +EuV1dTk8DUHlodcekWODRjY8/aGZlsguL+QqTgJWqjJBLJeLhbbZtq9y96QOSp3
            gi75U2roWU/QKs3VhBTSGRKGUyiKlQCKCySEUbVccrpJHAGsP8q51Th4e6dw263r
            TjVjSzZL1jkNTWz/xjvdfqd+fj+3C7mYWo5xb2cmd9yJiBDxglQMcj+2NTjDDGCw
            fmgvuxeP2kQZgBaSfSMueuOLO/Bk0pGqRCO/yVA5O//1cTwuSx7PZi1j3YCjs7HF
            Ib2j1yCYfXzA1X7Ay829Sx0CjxsHW1qKB+zb2y45uF2wpnqRcmCn0DoUlhASE6P8
            9rC3Mutkdz1RhzJepuD7CjxbOVZkHohLqfN9TrJLMiqvGDpngmIh6uAqhRIisPUN
            soi1CbzmslFOczR46K7d9YE7W02+xQ2y3I33tWWCpc+qUZkGj7X1PzGYxiQ9h5v5
            0y4jb89yyM9Y3Fq2BwVVUYT0oygFfpzmnsqrmsjyTEEDNzahIuIzyADKB7NgfaHS
            XgHF8XGkAwgEX7rUeLxtQ/9Gb7t05g/FKiZ8PXI0t1iIbVH02YDa9c9mNQ/zwkDo
            EWn+mPHUcBSnxIIBATOzytHGGxSUXhnlvgx9Thn7iEQX4WZvjlf+KFkxKxV1pZU=
            =KsNH
            -----END PGP MESSAGE-----
          fp: DE99604016EF8893AD54FDE83BC85C121EA96233
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
