---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: coffee-shop-2
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/Jonnobrow/coffee-shop.git
  ref:
    branch: coffee-shop-2.0/initial-migration
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include flux directories
    !/kubernetes/coffee-shop-2
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/coffee-shop-2/cluster
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: coffee-shop-2
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
