apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-app
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: cnpg-system
  path: ./kubernetes/coffee-shop-2/apps/cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
