---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-pv
spec:
  storageClassName: downloads
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.4
    path: /mnt/jbhdd/tmp-media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-pvc
  namespace: downloads
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: downloads
  resources:
    requests:
      storage: 1Mi
