---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate-bot
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://docs.renovatebot.com/helm-charts
      chart: renovate
      version: 31.45.0
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: renovate/renovate
      tag: 31.28.5
    cronjob:
      schedule: "@hourly"
    renovate:
      config: |
        {
          "platform": "github",
          "endpoint": "https://api.github.com",
          "autodiscover": "false",
          "repositories": ["Jonnobrow/coffee-shop"],
        }
    secrets:
      RENOVATE_TOKEN: "${SECRET_RENOVATE_TOKEN}"
      RENOVATE_GIT_AUTHOR: "JonnobrowRenovateBot <renovate@jonnobrow.co.uk>"
