---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN}"
  namespace: cert-manager
spec:
  secretName: "${SECRET_DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
  - "${SECRET_DOMAIN}"
  - "*.${SECRET_DOMAIN}"
