apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 5m
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      version: 3.1.8
      sourceRef:
        name: itzg
        namespace: minecraft
        kind: HelmRepository
  values:
    image: itzg/minecraft-server
    imageTag: java8-multiarch
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "VANILLA"
      difficulty: normal
      gamemode: survival
      motd: "Welcome to the Beebcraft Server!"
      pvp: true
      worldSaveName: beebcraft
      memory: 2048M
      serviceType: LoadBalancer
      loadBalancerIP: 192.168.0.241
    persistence:
      storageClass: "local-storage"
      dataDir:
        enabled: true
        Size: 10Gi

