---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NETWORK_K8S_CLUSTER_CIDR: 10.244.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.96.0.0/16
  NETWORK_MANAGEMENT_CIDR: 192.168.0.0/16
  METALLB_LB_RANGE: 192.168.6.1-192.168.6.255
  LB_TRAEFIK_IP: 192.168.7.1
