apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: home
spec:
  interval: 5m
  releaseName: paperless
  chart:
    spec:
      chart: paperless
      version: 7.0.1
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: jonaswinkler/paperless-ng
      pullPolicy: IfNotPresent
      tag: 1.5.0
    env:
      COMPOSE_PROJECT_NAME: paperless-jb
      PAPERLESS_REDIS: redis://localhost:6379
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_ALLOWED_HOSTS: "paperless.${SECRET_DOMAIN}"
      PAPERLESS_CORS_ALLOWED_HOSTS: "https://paperless.${SECRET_DOMAIN},http://localhost:8000"
      PAPERLESS_SECRET_KEY: "${SECRET_PAPERLESS_SECRET_KEY}"
      PAPERLESS_ADMIN_USER: "${SECRET_PAPERLESS_ADMIN_USER}"
      PAPERLESS_ADMIN_MAIL: "${SECRET_PAPERLESS_ADMIN_MAIL}"
      PAPERLESS_ADMIN_PASSWORD: "${SECRET_PAPERLESS_ADMIN_PASSWORD}"
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created}-{title}"
      PAPERLESS_DBHOST: paperless-postgresql.home.svc.cluster.local
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "note-multiple"
        hosts:
        - host: "paperless.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - "paperless.${SECRET_DOMAIN}"
    additionalContainers:
      - name: broker
        image: redis:6.0
        imagePullPolicy: IfNotPresent
      - name: database
        postgresqlPassword: paperless
        postgresqlUsername: paperless
        postgresqlDatabase: paperless
        persistence:
          enabled: true
          storageClassName: local-path
          accessMode: ReadWriteOnce
        image:
          repository: bitnami/postgresql
          tag: 13.4.0
        volumePermissions:
          enabled: true
        psp:
          create: true
        rbac:
          create: true
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data-pvc
        mountPath: /usr/src/paperless/data
      paperless:
        enabled: true
        existingClaim: paperless-scans-pvc
        subPath:
          - path: media
            mountPath: /usr/src/paperless/media
          - path: consume
            mountPath: /usr/src/paperless/consume
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1024Mi


