apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: home
spec:
  interval: 5m
  releaseName: paperless
  chart:
    spec:
      chart: paperless
      version: 6.0.0
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: jonaswinkler/paperless-ng
      pullPolicy: IfNotPresent
      tag: 1.4.5
    env:
      COMPOSE_PROJECT_NAME: paperless-jb
      PAPERLESS_REDIS: redis://localhost:6379
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_ALLOWED_HOSTS: "paperless.${SECRET_DOMAIN}"
      PAPERLESS_CORS_ALLOWED_HOSTS: "https://paperless.${SECRET_DOMAIN},http://localhost:8000"
      PAPERLESS_SECRET_KEY: "${SECRET_PAPERLESS_SECRET_KEY}"
      PAPERLESS_ADMIN_USER: "${SECRET_PAPERLESS_ADMIN_USER}"
      PAPERLESS_ADMIN_MAIL: "${SECRET_PAPERLESS_ADMIN_MAIL}"
      PAPERLESS_ADMIN_PASSWORD: "${SECRET_PAPERLESS_ADMIN_PASSWORD}"
      USERMAP_UID: 1001
      USERMAP_GID: 1001
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "note-multiple"
        hosts:
        - host: "paperless.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - "paperless.${SECRET_DOMAIN}"
    additionalContainers:
      - name: broker
        image: redis:6.0
        imagePullPolicy: IfNotPresent
    persistence:
      paperless:
        enabled: true
        existingClaim: paperless-scans-pvc
        subPath:
          - path: data
            mountPath: /usr/src/paperless/data
          - path: export
            mountPath: /usr/src/paperless/export
          - path: media
            mountPath: /usr/src/paperless/media
          - path: consume
            mountPath: /usr/src/paperless/consume

