---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: home
spec:
  interval: 5m
  releaseName: paperless
  chart:
    spec:
      # renovate: registryUrl=https://djjudas21.github.io/charts/
      chart: paperless
      version: 9.2.4
      sourceRef:
        name: djjudas21
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      pullPolicy: IfNotPresent
      tag: 2.10.2
    env:
      COMPOSE_PROJECT_NAME: paperless-jb
      PAPERLESS_REDIS: redis://localhost:6379
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_ALLOWED_HOSTS: "paperless.${SECRET_DOMAIN}"
      PAPERLESS_CORS_ALLOWED_HOSTS: "https://paperless.${SECRET_DOMAIN},http://localhost:8000"
      PAPERLESS_SECRET_KEY: "${SECRET_PAPERLESS_SECRET_KEY}"
      PAPERLESS_ADMIN_USER: "${SECRET_PAPERLESS_ADMIN_USER}"
      PAPERLESS_ADMIN_MAIL: "${SECRET_PAPERLESS_ADMIN_MAIL}"
      PAPERLESS_ADMIN_PASSWORD: "${SECRET_PAPERLESS_ADMIN_PASSWORD}"
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created}-{title}"
      PAPERLESS_DBHOST: localhost
      PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
      # Resource consumption params
      PAPERLESS_OCR_PAGES: 1
      PAPERLESS_TASK_WORKERS: 1
      PAPERLESS_THREADS_PER_WORKER: 1
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_OCR_MODE: skip
      PAPERLESS_ENABLE_NLTK: "false"
      PAPERLESS_CONVERT_MEMORY_LIMIT: 128
      PAPERLESS_CONSUMER_INOTIFY_DELAY: 5
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "note-multiple"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - "paperless.${SECRET_DOMAIN}"
    additionalContainers:
      broker:
        name: broker
        image: redis:7.2
        imagePullPolicy: IfNotPresent
      database:
        name: database
        image: bitnami/postgresql:17.2.0-debian-12-r3
        volumeMounts:
          - mountPath: /bitnami/postgresql
            name: paperless-db
        env:
          - name: POSTGRESQL_PASSWORD
            value: "paperless"
          - name: POSTGRESQL_DATABASE
            value: "paperless"
          - name: POSTGRESQL_USERNAME
            value: "paperless"
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data-pvc
        mountPath: /usr/src/paperless/data
      paperless:
        enabled: true
        existingClaim: paperless-scans-pvc
        subPath:
          - path: media
            mountPath: /usr/src/paperless/media
          - path: consume
            mountPath: /usr/src/paperless/consume
      paperless-db:
        enabled: true
        existingClaim: paperless-db-pvc
        mountPath: "-"
    resources:
      requests:
        memory: 512Mi
        cpu: 2000m
      limits:
        memory: 1024Mi
