---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-scans
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /scans
    server: 192.168.4.4
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans-pvc
  namespace: home
spec:
  storageClassName: nfs
  volumeName: paperless-scans
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
