---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-scans
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: paperless-scans-pvc
    namespace: paperless
  nfs:
    path: /mnt/jbhdd/scans
    server: 192.168.4.2
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans-pvc
  namespace: home
spec:
  storageClassName: nfs
  volumeName: paperless-scans
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
