---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 1h
  targetNamespace: kube-system
  path: ./kubernetes/coffee-shop-2/apps/kube-system/csi-driver-nfs
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
