apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: 9.0.0
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.7.5
    env:
      TZ: "Europe/London"
      JELLYFIN_PublishedServerUrl: "jellyfin.jonnobrow.co.uk"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
        - host: jellyfin.jonnobrow.co.uk
          paths:
          - path: /
        tls:
        - hosts:
          - jellyfin.jonnobrow.co.uk
          secretName: jellyfin-tls-cert
    persistence:
      config:
        enabled: true
      cache:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
      music:
        enabled: true
        existingClaim: jellyfin-music
      shows:
        enabled: true
        existingClaim: jellyfin-tv
      movies:
        enabled: true
        existingClaim: jellyfin-movies
      youtube:
        enabled: true
        existingClaim: jellyfin-yt
