apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-music
  namespace: jellyfin
spec:
  storageClassName: nfs
  volumeName: music
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv
  namespace: jellyfin
spec:
  storageClassName: nfs 
  volumeName: tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: jellyfin
spec:
  storageClassName: nfs
  volumeName: movies
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

