---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1342
    env:
      TZ: "Europe/London"
    hostname: sonarr
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
        hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 2Gi
      tv:
        enabled: true
        existingClaim: jbhdd-tv-pvc
      downloads:
        enabled: true
        existingClaim: jbhdd-downloads-pvc
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
