apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 3.30.0
      sourceRef:
        name: ingress-nginx
        kind: HelmRepository
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
        tag: v0.46.0
