---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  releaseName: frigate
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: frigate
      version: 8.2.2
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: blakeblackshear/frigate
      tag: stable-amd64
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "camera"
        hosts:
          - host: "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "frigate.${SECRET_DOMAIN}"
    configmap:
      config:
        enabled: true
        data:
          config.yml: |
            mqtt:
              host: mqtt.server.com
            cameras:
              rodney:
                ffmpeg:
                  inputs:
                    - path: rtsp://${SECRET_TPLINK_USER}:${SECRET_TPLINK_PASS}@192.168.0.180:554/stream2
                      roles:
                        - detect
                        - rtmp
                    - path: rtsp://${SECRET_TPLINK_USER}:${SECRET_TPLINK_PASS}@192.168.0.180:554/stream1
                      roles:
                        - record
                detect:
                  width: 1280
                  height: 720
