apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 5m
  releaseName: paperless
  chart:
    spec:
      chart: paperless
      version: 6.0.0
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  valuesFrom:
    - kind: Secret
      name: paperless-secrets
  values:
    image:
      repository: jonaswinkler/paperless-ng
      pullPolicy: IfNotPresent
      tag: 1.4.5
    env:
      COMPOSE_PROJECT_NAME: paperless-jb
      PAPERLESS_REDIS: redis://localhost:6379
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_ALLOWED_HOSTS: paperless.jonnobrow.co.uk
      PAPERLESS_CORS_ALLOWED_HOSTS: https://paperless.jonnobrow.co.uk,http://localhost:8000
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
        - host: paperless.jonnobrow.co.uk
          paths:
          - path: /
        tls:
        - hosts:
          - paperless.jonnobrow.co.uk
          secretName: paperless-tls-cert
    additionalContainers:
      - name: broker
        image: redis:6.0
        imagePullPolicy: IfNotPresent
    persistence:
      config:
        enabled: true
      consume:
        enabled: true
        existingClaim: paperless-scans-consume
        mountPath: /usr/src/paperless/consume
        readOnly: false
      data:
        enabled: true
        existingClaim: paperless-scans-data
        mountPath: /usr/src/paperless/data
        readOnly: false
      export:
        enabled: true
        existingClaim: paperless-scans-export
        mountPath: /usr/src/paperless/export
        readOnly: false
      media:
        enabled: true
        existingClaim: paperless-scans-media
        mountPath: /usr/src/paperless/media
        readOnly: false
