apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secrets
  namespace: paperless
spec:
  encryptedData:
    values.yaml: AgCPDHT4FOAMh+ql8HVfZO8vjYv14qVjCcepN+Zw4OiSa/4hj82RFnUjhiTaiYjTnmI5OTpuUraBgx1GInMQCpkOROwFWzq1yad9Z28+9xtj4hbZrBDfT1JSOC1oqEK/UKQwl9Ff5U9l04uDLD3ZIy80LkJltkeZ1yaEjSw509bXLRfmozPfkxI7DYZcRgpXjQZP+ryXpnxHSwcRb9sAqklpWT90VQmHTJT3ejzwzkY1Nf0bVbtF3FGbx41DpeDTG4bSGUaqCLI8h5dRyvV88fgVQVundOMQhD1gplR11mIDknEnNhp5GazDjHx1E/TSWEmRliA4r0y2JBocYNdwLcc8sfNA4goQriDvEdK7W7AcCRjaWAHGgHrUdNIuvf+lxqdEgBKQf0sUCnAnwgD+3zs0AH9jlERmKfFqBHWs8ANZ5tdCVhtj/qdXPWj/cblzt1wmTGRwHtwWd8RI1hshbSFfqlKxpElP/9jrismjwaoyRJ9IXwy4Tvkbgf79V9ENAN8mGK2ogv+1F92bDM3zhQB+7P5CAYYcTqRuCFNfUGQKun073zD9R28MMlDfiJWX53v5Fyf5h99h/rvfdT+0ZjlvUmFab4zEbdDsNZzRrEcPBHI45HBifJuXCQtGKQ9DNGPmdeDsKqZL6Vq4T8FR1Qk4cMSN+YVw9IlbeSlZdXz1Sl3gGAzCUNAhPOdhd7g/H8R2q2Sx6fMnrYnEP/8DMaUXlfDaw5JHgP1FxpTdDjENg5JzuZUQ2IZImm4+l8auQ+cfXGH9IvSgjwfGl3r9BsSfagr3GnlcaSjDL/l0EdvSu6qK0vXMTSpbJQrD2M4FwO9CILYpWMbbwswuQQm4a/F9R8r2cGlRyjbXNCxxE5/ymXgTRGT4CSMHo6089x/pgV7crI/qPgrXoaL2s58jlll0LWLcxNQ7Qbrycph5GPSz1oOIqmWSZU4lxfIg3TFDhTRyXsIm7BCOPxEajSm7NhFfWCt0d4h5uQdDUFHyvKjdwNFt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: paperless-secrets
      namespace: paperless

