apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans-data
  namespace: paperless
spec:
  storageClassName: nfs
  volumeName: paperless-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-data
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/scans/data
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans-consume
  namespace: paperless
spec:
  storageClassName: nfs
  volumeName: paperless-consume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-consume
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/scans/consume
    server: 192.168.4.2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans-export
  namespace: paperless
spec:
  storageClassName: nfs
  volumeName: paperless-export
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-export
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/scans/export
    server: 192.168.4.2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-scans-media
  namespace: paperless
spec:
  storageClassName: nfs
  volumeName: paperless-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/scans/media
    server: 192.168.4.2

