apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.3
      sourceRef:
        name: ingress-nginx
        kind: HelmRepository
        namespace: flux-system
  values:
    controller:
      ingressClass: nginx
      replicaCount: 1
      image:
        registry: k8s.gcr.io
        image: ingress-nginx/controller
        tag: v1.0.2
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      extraArgs:
        default-ssl-certificate: "networking/${SECRET_DOMAIN/./-}-tls"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi 
