apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media-management
spec:
  interval: 5m
  releaseName: prowlarr
  chart:
    spec:
      chart: prowlarr
      version: 4.0.1
      sourceRef:
        name: k8s-at-home
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.1.0.421
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
        - host: prowlarr.jonnobrow.co.uk
          paths:
          - path: /
        tls:
        - hosts:
          - prowlarr.jonnobrow.co.uk
          secretName: prowlarr-tls-cert
    persistence:
      config:
        enabled: true

