---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: openebs
      version: 4.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
  values:
    localpv-provisioner:
      rbac:
        create: true
      localpv:
        image:
          registry: quay.io/
          repository: openebs/provisioner-localpv
      hostpathClass:
        enabled: true
        name: local-path
        isDefaultClass: false
        basePath: /var/lib/data/openebs

    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false

    zfs-localpv:
      enabled: false

    lvm-localpv:
      enabled: false

    mayastor:
      enabled: false

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
