---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 12.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.8
    env:
      TZ: "Europe/London"
    hostname: qbittorrent
    podAnnotations:
      setGateway: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-auth@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
        hosts:
        - host: "qbittorrent.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - "qbittorrent.${SECRET_DOMAIN}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
        - host: "qbittorrent.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "qbittorrent.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      downloads-jbhdd:
        enabled: true
        existingClaim: nfs-downloads-pvc
    podSecurityContext:
      supplementalGroups:
      - 5600
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        memory: 1024Mi
