---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openhab
  namespace: home
spec:
  interval: 5m
  releaseName: openhab
  chart:
    spec:
      # renovate: registryUrl=https://charts.truecharts.org
      chart: openhab
      version: 7.0.4
      sourceRef:
        name: truecharts
        namespace: flux-system
        kind: HelmRepository
  values:
    image:
      repository: tccr.io/truecharts/openhab
      tag: v3.3.0
    ingress:
      main:
        enableFixedMiddlewares: false
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
        hosts:
          - host: "openhab.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "openhab.${SECRET_DOMAIN}"
