---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: home
spec:
  interval: 5m
  releaseName: photoprism
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: photoprism
      version: 6.5.0
      sourceRef:
        name: k8s-at-home
        kind: HelmRepository
        namespace: flux-system
  values:
    image:
      repository: photoprism/photoprism
      tag: "20220121"
    env:
      PHOTOPRISM_DEBUG: false
      PHOTOPRISM_PUBLIC: true
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_AUTHOR: "jonnobrow"
      PHOTOPRISM_SPONSOR: true
      PHOTOPRISM_EXPERIMENTAL: false
      PHOTOPRISM_ADMIN_PASSWORD: "${SECRET_PHOTOPRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_STORAGE_PATH: &storagePath /photoprism/storage
      PHOTOPRISM_ORIGINALS_PATH: &originalsPath /photoprism/originals
    persistence:
      config:
        enabled: true
        mountPath: *storagePath
        existingClaim: photoprism-storage-pvc
      originals:
        enabled: true
        mountPath: *originalsPath
        existingClaim: photoprism-photos-pvc
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "camera"
        hosts:
          - host: "prism.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - "prism.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 2Gi
