---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-photos
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: photoprism-photos-pvc
    namespace: home
  nfs:
    path: /mnt/jbhdd/photos
    server: 192.168.4.2
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-photos-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
