---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-storage
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/photoprism
  claimRef:
    name: photoprism-storage-pvc
    namespace: home
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mocha
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage-pvc
  namespace: home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
