apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: borgmatic
  namespace: paperless-ngx
spec:
  chart:
    spec:
      chart: borgmatic
      version: 0.9.10
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: gabe565
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controller:
      type: cronjob
      cronjob:
        schedule: 30 1 * * *
        ttlSecondsAfterFinished: 3600
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: paperless-ngx
                  app.kubernetes.io/name: paperless-ngx
    env:
      TZ: Europe/London
      BORG_PASSPHRASE: ${borg_passphrase}
      PGPASSWORD:
        secretKeyRef:
          name: postgresql-app
          key: password
    persistence:
      data:
        enabled: true
        storageClass: nfs-csi
        size: 100Mi
        accessMode: ReadWriteMany
      ssh:
        enabled: true
        type: secret
        name: backup-box-ssh
      paperless-ngx-data:
        enabled: true
        existingClaim: paperless-ngx-data
    configMaps:
      config:
        data:
          # language=yaml
          config.yaml: |
            repositories:
              - path: ${borg_repo}
                label: backup-box
            source_directories:
              - /paperless-ngx-data
            archive_name_format: "paperless-ngx-{now:%Y-%m-%d-%H%M%S}"
            ssh_command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=ERROR
            retries: 2
            retry_wait: 10
            keep_daily: 90
            keep_weekly: 24
            keep_monthly: 24
            keep_yearly: 20
            check_last: 3
            postgresql_databases:
              - name: paperless-ngx
                username: paperless-ngx
                hostname: postgresql-r
                options: --no-owner
                format: plain
