---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-app
  namespace: flux-system
spec:
  targetNamespace: openebs
  interval: 10m
  path: "./kubernetes/coffee-shop-2/apps/openebs/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: coffee-shop-2
  wait: true
  patches:
    - target:
        kind: StorageClass
        name: local-path
      patch: |
        - op: add
          path: /volumeBindingMode
          value: Immediate
