---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: development
spec:
  interval: 5m
  releaseName: jenkins
  chart:
    spec:
      # renovate: registryUrl=https://charts.jenkins.io
      chart: jenkins
      version: 3.12.0
      sourceRef:
        name: jenkins
        namespace: flux-system
        kind: HelmRepository
  values:
    controller:
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-ips@kubernetescrd"
          hajimari.io/enable: "true"
        hostName: "jenkins.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "jenkins.${SECRET_DOMAIN}"
      image: "ghcr.io/jonnobrow/coffee-shop/jenkins"
      tag: "0.1.0"
      installPlugins: false
      JCasC:
        enabled: true
        defaultConfig: true
        configScripts:
          unclassified: |
            unclassified:
              globalLibraries:
                libraries:
                  - name: "jonnobrow"
                    defaultVersion: "main"
                    includeInChangesets: false
                    retriever:
                      modernSCM:
                        scm:
                          github:
                            repoOwner: "jonnobrow"
                            repository: "coffee-shop"
                            repositoryUrl: "https://github.com/jonnobrow/coffee-shop"
          jobs: |
            jobs:
              - script: |
                  folder('Seed')
              - script: >
                  job('/Seed/Job_DSL_Seed') {
                    scm {
                      git {
                        branch 'main'
                        remote {
                          url 'https://github.com/jonnobrow/coffee-shop.git'
                        }
                      }
                    }
                    triggers {
                        scm('*/15 * * * *')
                    }
                    steps {
                      jobDsl {
                        targets 'ci/lib/seed/Seed.groovy'
                        removedJobAction 'DELETE'
                      }
                    }
                  }
