---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: development
spec:
  interval: 5m
  releaseName: jenkins
  chart:
    spec:
      # renovate: registryUrl=https://charts.jenkins.io
      chart: jenkins
      version: 3.12.0
      sourceRef:
        name: jenkins
        namespace: flux-system
        kind: HelmRepository
  values:
    controller:
      image: "jenkins/jenkins"
      tag: "2.332.2-jdk11"
