apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-app
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: ingress-nginx
  path: ./kubernetes/coffee-shop-2/apps/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: coffee-shop-2
