apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-mealie
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/databases/mealie
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cappuccino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-mealie
  namespace: mealie
spec:
  storageClassName: local-path
  volumeName: database-mealie
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
