apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 5m
  releaseName: mealie
  chart:
    spec:
      chart: mealie
      version: 3.0.1
      sourceRef:
        name: k8s-at-home
        kind: HelmRepository
  values:
    image:
      repository: hkotel/mealie
      tag: v0.5.1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/tls-acme: "true"
      tls:
      - hosts:
        - mealie.jonnobrow.co.uk
        secretName: mealie-tls-cert
    persistence:
      config:
        enabled: true


