apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      version: 2.6.5
      sourceRef:
        name: nextcloud
        kind: HelmRepository
  valuesFrom:
    - kind: Secret
      name: nextcloud-secrets
  values:
    image:
      repository: nextcloud
      tag: 21.0.2-fpm-alpine
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: nextcloud-redirect@file,nextcloud-wellknown@file,nextcloud-bodysize@file,headers-default@file
      tls:
        - hosts:
            - nc.jonnobrow.co.uk
    nextcloud:
      host: nc.jonnobrow.co.uk
      extraEnv:
        - name: TRUSTED_PROXIES
          value: traefik.kube-system.svc.cluster.local
        - name: OVERWRITEHOST
          value: nc.jonnobrow.co.uk
        - name: OVERWRITEPROTOCOL
          value: https
    nginx:
      enabled: true
      image:
        repository: nginx
        tag: 1.19.10-alpine
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql.nextcloud.svc.cluster.local
    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: database-nextcloud
      image:
        repository: bitnami/postgresql
        tag: 13.1.0
      volumePermissions:
        enabled: true
      psp:
        create: true
      rbac:
        create: true
    redis:
      enabled: true
      usePassword: true
    persistence:
      enabled: true
      size: 25Gi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: true
    lifecycle:
      postStartCommand: ["/bin/sh", "-c", "crond"]
