apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgBEYlPT1mt8vwyD7EtlGm5u6sGhxhKyTX1A/oUsNDL6nfQBx6NtwyEKdLAnv5HKogdSix7kRCv/gZ7/nVqw8Xf7MbF6kk8IP/bO1mZdH26FWbwCfC8kUH6VWBEJtNtcMO9cFOZXVcfafOo9k2EldHnO6dkEZODDbUt5lJDCQoJS4vyxNr71xzv4tPoauoEowHB6SfK+9FG1quateOeKbf3Q8qt0WKNfsj/67xFoHnIjYVqN3lhs92jO5GQHsuzpw0XY9zWTHR5+QxYka5kPpcc6wrxWPBUYGdz38sdEAfAiSAufPIxDfcKfdE69NqcmO2WOhopW59xa94J+ML7EKr0Uw8zk6QGHQ0pjVofHxDU8nzxyJJQxTc3fMthy9HF5T+uSmFQBsX6bfqrOUxSCaHc/gbAbZCIaGZPEZomCBkkwf9SIi+WKAeqWLI2y5NAxG8eSIvbIHcCWPOgxBEwrX9QxFKV+rL9B/T5koUlOeZiZTVk2UpAXm06//eVOXMTtfJjCS5FZqhyQQr65iFhyq7CjoXJHk0Rx1mnaW5Q0CBM0RZBPXIoIc6yxnouzjpFr+ln047Owu6qw8NW49Xbgf+7ZFbJTyvAuC8oVAPYFAGAkkil+IvsPdMgK+hG3gX4PFy8Eb4KHcZu6Iw57g+FPaJ6hR96uu+RTPzklJslMY0qRsBgaoKhpSY0X41katdhKe/HHR/nFY12BOS7WTfsjaNLumxpItpQCACGk7kNtu4fA6D5gwoaqRV0DFOl7dFhk//iKHtLSWJO4MKauD4U2Bc3eyKxWMMhZLbxE51RON5C8h2zPNSeRF+65FtEzdjVd3PHP5bYc3FVHIi7S3N7Oyz82vY3AmFeetWHpUWodmNbi4C6cqPR12r+c7f3Ocjbds8tzmH0JsE2nOjlDSO87ZOVZ/HJDLRJcrIM5qUWDYYyua4ipuhiI8a/SuY0ESRRA0iVTpAzEJ8orcNHelH+Nzo7TLi/mWGW5JUUUkuFcCojIlYDS7FXRQAxKQYOczGRArhYn30UtM/hPlpGUIYCGwRfhcd+k+a5T3BZkZ6/l6bIcJxiWj7BIiEzbWDGMgbR7YK9lf4IDy1sYJ6JMfjx9l8g5BMIPR1k5xL63cLMgPOWdmTqY9Ee7XOQKn4WUCF5d+C/0kkaJMlZeEnZy0WQUs/YjGkq6p/25BWsfPZQDK/wyq7qeyUw7cR2zkoEo/bT1nPLP1bD505YDEzoUPVvqksuXeoqHTfIGfETK6aOXigAKwvqRiantrlNElgljUQNN8VeamamfPpS99962T5x8zlJlPj3SzqKhNRJS2rXNGB6ikSqLjl3oBw4jXCwIkeIi+2ZwxcwEem7gNQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

