apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgC+ylp8rPOYRroHZv1v4qgX/6p3DaUWFSpDQdf93JOqjn82VRCO96Jz8cQNwoUcNIvM4B++9qXQxqrl6rDNPb7q2uE0YEZJ0SWQb/LTENo/AfFt+fH18uqeuPDu12jSRp+4nOLTulZwxBUs5rez11FmaNUil4ii6lZ9OxOPma0crgAHQklY8pUwuQnb7+uwR6F8Zgq5oivqLS999lwKcNvP8CSgV0IE/LRbHZiqdUX42lkStOZ+6X+L3yK/SyIyI7S4xCimd6+h19WjCm/fdh5DIhbIpu0hTO/Cpe7mIz3j3zskdIfFVnYrSF+EtEnbxdpfhAEzjwB9M74GN7ssT5OWxrV0N/0nQ0AeDWjT7mp4Mnc96wBz5zswMxHFbmJEMyBZ6PLI3UTZ7FP3knhRC1sCePHFMeBKW+XiWQu9dK2fiNLgy0YsJswgAFSiG5opUnL6crksYZmu7nr6/HtiBNdvMjFJctp4RoK1Wm1q5s2GcZR5WOkIT9zukA2go3eXPl+eD1fFYHjJ7vBvsd1R4e0/0oLiAtKqBFVW7TaWGMvIj7aZO09N4a1hUqA030loCxs484FeAzNooJHYGAUVJEOuOXC2uf0GZrv0bGFo7SMQSFmA6+1d66AtmnCzro5l5PpQ8VdS7X3wB6eb+KOXVv+hLbZFdjuGnlDUrd8nkpUt5CONMs3tulGbW7hZdP/G73pQyijsiwakH684kYGYYdZPfTFBN6T89Q3NllzpAqarddiE1LX0Ok/52hFvsdbcAskcOZK0dCDA42KC/+lR/lJ7IkmlfRt5U72SlLugSlexKKjBknAGZcDQQAU4pkxCBpaz2nefmoDQgefQAEeuBFnBSrmz/D5k5RbyL8iKmKj4mpPzloQOO4kmaR56QrX6c6W3hXzBgYhJmFlvp02aI/ZwaITURvcRMhyGUUNHurvFg8TbHYF8oYKMna/HYBpRUKswne8nf4IKznYlbeXZJFvyyvxU1aB12H7pr9qpYuFds1J60cI0zn2Be9Z2oqnFKwR4snVoLG9hqBnP9oSaZgwZj3sDHsfAuYO56S5yRn3xXJQbjd6uhIdxkb5EwkSMtVjdBSPcq29WC3NMXCCiggVtBiz9vaLcD8NTaaQPF05L7pjTMNQBGl2Qf/1RILECjXdMU4ZVoGTxDR64aruhSW2YbbQKQQHwFlAC4qrCyrDLhOYG2LSZz8j/4D7bjXX14cyV0+p6sfmlvZgPJ/eJ/q+9f7Z08RHLbDJB5/TbEHc0IzBbRCEjmz1SpnciQSCx5Ov9ZQ3q3r88yZBXUdJPotz2oDmG6xcinoMqshgtusg=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

