apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCKqmogoR274GKJsP9FUqIYA7zUs1ZgliEisJ/4vg3feIe9wxlGuhJyWxInJGUPPVl3nJhFabSowQq6rB27nde8+4FJxO5cfEP2AlSOc4WIRY4zXC4lQ7fY4gTDZiYti5bHHAXzJypcRTkws6dJ8/SYz2mJ1nNyWaGvBFRLa98wEjljf5RWurj1brAqcUhG2s3OGj9CcdJLc9Imh+SeyJvu8frH3dGMQtJ2ZWTdG+NYUCHDGJRH/8aGBkayc7YtAGMcu9XskQRGm+JLof0xAHs323HwC964Q7/Uaa5jjki/320rSo1rEpbiwKMkZEe3/TuRSMnqXrmoMWJRwyw48LYIuieEggU4FISmkj2RA89VmZEhEPzOkZuJYOnkZ4nuhbBTiMcQ4d3CfqoSEusKnfMK5fNud6QhoZDokGJFHppgcJ/1Bo/7O3Tw+eB96KQk2RY1z/FLaDPk/UIt1pjINCb01XPQYND5xhAyP4eFKEot0nA0dKxRNK9fWdI5RNAEpe9ymn44E39qA8F80e/6Qm3e1YR7T/O+94nk0Y+1OlzFb84E/r6lzp22ROMwbiogt2Don/HrV2/cAv6EgWu8KVjvO6n8awcZ7+ZBzQhU3+0XGImebeoWpnew7zM+M2Zl150iyyKbPwpDN64NNKdZ53vouapj0UHKXHjkiX7E6313pVqvQhxWVXCbC5Qqb6byoUhR3DO5Ml8LNXF2ntJ5n1PE7w2daLxh37adBnnhByHt7HgxxLjkKlR0FarUFmRm3epEKYZ1JCJh5txnIrcm18RPmgclYX4oCyWEH/tc56G6+n1Z1rpakaPdMhgxsvZgu42Zz4OtszSMma9ZYes2AaMrF501Ar8pnJronF2KWWHpgBmw4q/XDFfwMCvnYzn+e+1LyGbLo2lX0mwNP49g/Pg9ZnKoYsX6n5fLYXAFE5JXiPp4HYRzb2w+ZAaoECWfoa8liFgyhpACPVYYmt4JJixXomjIGwH7lRorftp4FmbtcNGvNSWlNETDthqecqsvXtuZmPtk/d8+Hco2clA3mjSXIHWvHHHOK7ymqo2F0E5mPqHANdJgWpLYnjiLlqbxUq2v15CdvSue4Ffg4SubaNsXyC+K1jDGsE+HZPd9+F50djCrOoJKxXGtvAUGpJIgtzML3pTIVxIP3CxNVLLO5wKLseqfRMxjeoNoBkLm8lv2Y2cDGaaEVBvtPtC0C0bChsLfwHmPuGXiFTrIaqBx/dKJZZPjg3wjW7kmyeGRYSFmfNmzQTNlHM9HBiuF4LgSrqjCpXSp1IaCLzVvPwbmkX7Mylw5ju1Jskt+LDwle7E2EUqsqxhunH9YQOT9r7lgUIKx0uDeocaJqRI7l6V7Fes0Ou24Oc+enknBOijQoA==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

