apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCmzJmir3KFDf7PRUOOOWSNjI2lynxTasQG2bzWcAZ3j+y1hL550mlN8coD8kfjJSpdOaBS1+9ay//Qzusni9jaRjnesyMmkAPT8iJB7bupS2ZohyP1E0n/X5IJ6rnpb+R9HiCs16LL2SYgE0eGKjDkBn+j04nc0UsiY5ghhDbYS6flSXRM3egdNyF0LDqhNYoHpdS0MgxBr7xEZn6tTCns23rQLP8rBvT+4v4AJLy171xR/IY0PvIUS6r5p9gIMOa1SZtEuSteUL4oSkfvICfSyET606dNVmBGFNVU3Qxe1TOSfgrrneil1ZkZBLTXXygfCZrtHGBU/+jYUm26JEDzyVtS3nViaCM5JBG9re7k7qVJCwiEdje0IJ1+HgbQKMeE8bJBO/WW23Gw/Lps+F9HQ9eeaGYJfZsSnmtqmektbXvwhLwKKDezsYi2PYqcVgG22qtVfaQhxHnnUN/OvMI54njUBGVb9XhMPrr7rMtXRAkpJ8OZtlZX6+lQUaPRA66mBkIhnfn7d0vtrlD6nJzr+F1VevrM4OcQHXub4Tsh9sb30szzwpPJiBdnaCkwv4y8BRVBWuB93fyjWSfI+Ab6Bnhc56Jjyhw8EQMMXamzfVIekco7yHrN9IcTkYszm8KIDgaic9MbLexeVU1BxGlxgZs5SVxEuVRg2OE2dQ1LK3eXVIMtkapwHIQn+1mxcJb772V8IwDtt9+liAyp8arSfeREt2cYX4rC4qUmqa9jWkcWEU7S2pWUfRAKXEuFb030wQOcVmes9Rb1LA/P0jjxICnwpmxM5IdviIjXRfApR56nnGQ7453fVyBOPZj7/68vINkZycE7Fl0NTNdETleNSC47kkGA7Bboe+FmxRn7YmVYz1GMpWOEwthRxK5LCp+fo2A4kg0ggngQwtCgnNivxxdrIviDPslEx5TN8bnDMykQulduW2QzXPe6hJoLaQH+8QmQGCYoQEAipVoXF6tzKJLqAR+ZB4S/fW7OjxwRkB4831vyTkg61nLKc47ZhODqJcZZlxwn5MMfklVXUHJud6Qqa+VZ7/4r7TPrap9e7Q6izOoMxo0tYVd0jfUp9yc6PQMAU2vcFF3/QWznlSYOcvXd5W+Zi8YJbdrxNWimGZ6CjaO/f5ZrWbvABb8HoKBVUQFzvM3mHhdhB3Exkm4N/Z2ItucMhzLMwspDfC4nrwBnwhiSSJAS6gLoFxlNMlwTpxoy20GEw5IEG+xdbW2+PiiKl6KXGrmtKRWtFuJjDpmbPnjTh7QO1UxPU9AYlsTlFXXJy1z6P898vwZTY+Tedsgt9p2WvrkS7M8OtZ0=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

