apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgDkNuXu+/e0cBIYWedT/bvlGuL0B6/jchq7meMnASR2YwCfYjjBH1MtlrD3NB2bMyVMF3bxzADldJAL0YDU7+ZYw5AmlvdhW1sp7BruKyIJQ2NSR26asc7y0L9U38owdg7Bra4ULvYiXmpU+iJRADurM3rVM3n32unWGYaeRCA1MpXwikO1KwL3vpwW2lShxiDQvYGGNQAoy21BIdB/WVpj21OnyzKbfwIymOKJHdWVV24sy2IgXOKYoLS48wXft+NMIGxyTfH1KDrWPHhTpR+Em/Dc87qTkwW67ffbXQg/g/y6xAVDuuytmvsmHPobj+vP+s4rVbivUhSCKrhKv5U25Xo2u9PYueSDXEkI74xJR2Nf9Jjgb6h3hIy9qdMV6tWMu4FRjkCkz7z8OntZdZHXtMW7IiVsUyc4xrVQnJFYR3s3rlrT51cwfivH+xUGQ6QOEtXMQmMCR1bLy/cJxC9c7vANlH7/0j0th6N/NdskVfxsEhO5fB0qK4+/Teq08akKUkAwK8CKzIE++zoPm0cOpI/tGRSEcMBkmICk/r7wuX+ILkmsVFwGKAzJ1/HnXda156f8PZXVGzpR6RUNq6GKnbh1XD8LOkmWehMPGkgwM6LOlRjcz2/03V0n0xVlLi17N+e7/0EJLgChGzPqd/fG9GKGLK/HzQRI9wN3x1PyFOEDhyOLDn6xSmvIXaIvSvazHDMPP07DCMVFhz3MY6gOfkF+tDBMR21eFcMOxbTHp7F+7cNdLjp+6u12dFUbzgwAPsKyuc0g+UBhCFcyLuEMeFHH7x80ID4fP+fPAluq0VsEuvqScEKFcPqfV30kv61or5SNxICB5Uly03YIAWQ1lg7tfWKYMhhGNDxN8z/7qwwlUVHgA9PPWXSIwmbZQZ8Y2lsU0v6yujdVvU1cCvKGz1UjsXgrym093yV2qZYaNZTN2nzPaRhhBh75D4x1b00clj0TMnKbWpAAkl82j9VF4j9aq2BebwMKrVUJUBfu+6Z10F17AlEdg1zcg2yCb3Y=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

