---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-scans
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/scans
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-scans
  namespace: nextcloud
spec:
  storageClassName: nfs
  volumeName: nextcloud-scans
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
