apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-nextcloud
spec:
  storageClassName: local-path
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cappuccino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-nextcloud
  namespace: nextcloud
spec:
  storageClassName: local-path
  volumeName: storage-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
