---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-photos
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/photos
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-photos
  namespace: nextcloud
spec:
  storageClassName: nfs
  volumeName: nextcloud-photos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
