apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgCkonM3QYldmQNgNBfF0JirsAcokn8UyY954qug1hAi2A/P8r8AKV71i2M7h71YUAIY/tUf5PYVVdqZsE8DWm3QcuP+dSEGob3XnywaLgV6YvWDM95g6tNDZqeim3BmhqLimOi+oq0H45HCRk4b9+xbJ4P6dH1KFdtFTQssG1wd13dxg3WNgEwNgLDeE7tn85acSidBVvYtEh1rF/6Rx1CQ8QWMj/BobmGJ5SLPJJhQ2Osoa9uGXQZFKsUPvlQcB8VaCBGPyRJ3vlTRlo/M5h5/uDRHKw2ktEls6An8ybkFi1ZtBEfRXcYR2tAEFjfmoR0XEH9hYR3Ov/1k0LZiXyQvw/ZeXYJFAxznpoM73YjcJKlIGxAH0IQtDuoarQT9TWhZ6758ZKs8RSm69puacjveNC9fvurlJMghXK5Tk6M1/a6HZxDRSMz+FwibHtIPIWaYEiz9r+esqu05vHP+7DM8wJwBNwjmwq9f13a1xNFfYXIHSyd0XcliIEuubOAd32WYIXebECQJBClmBqICMv7rI84ZLAsf0DaV7kVM6w1WYtZO+EeCLVKj0WVFu9CnFh22MgRvLUga2Ho0pYEQ5CeuD7s1R4CGWlBhUxw1nL7+TrbN04pjscl/k+qo9DkpaPASOoOIFFYFn/VEFQjHFcxDg4XsRi+3Ano/vzxtF5KuB6kT1YJgAO834mYkJ9KIXJzYiR2d66xs2rRdcrRfYPo/1dvQ9C+kzQSIrF8sEyNsQqKnXCuT
    email: AgCcUb8OJpn3OeJ64g0sFmoEo4O+O0yHMLez2qOyNnDKHQ2z3bPNtZjBC5sRl/wY3phShAC4BCsuPTT0UKmJoKdOKEdUAF5ydN9sWZwiJKerA+6JPWBECh9Pkj7zDREzPgcYEhWsMN/iWLe8q0+cMnIWCdMHA/q1qOF1zFhJKXkjzTSINgUqrQ4csAo4SsZht3fLkPWLFXj5tG7IL2avMiqEv3WG2Wxck2lXXvJ/cpJWH64wqkbsv4BNoYC26t55bDptKLed4ekX0FOCX5bpiSb3sIRqE3jfq4uHI8n1GX+HvurpUXfiztVcBgYkEdV9PzS7gLntJD3Er14dIMhPIa01kw1b+xFb6+JB9fsRfqo7LVjSqYVldfH875FEHw+ZjjoV09nlTKQkPkE8XumYhzI+m6XLUbvQ1l7jLUwBwsS7QCM8gA4LsjEYRVKaHKwnlFT7nxdMPINVDQMkVOMdhlENpWGurgFVOF4IgnLItvMPt9tSi4V6ZPTiHNO03YGCD433k4I8GSMrBIJDDcFotBq9izLDJHJQZ5unme8qGKYDnRAtQI5+FKcJZIz6fCLnv06gOXkkP6B5LlCY1Fv2CMpSc1tt9IMDbT4Zh3F1XzjIQlqIyHmxEN5i7bNzxIjXWUon60CQjasmZODtPPQJbcSNO05yqttPvVAZ7p8WVPykfpfXe2EVy+bMOaXEOEvKwra+ywd/dIbWVk6YktASqeAxJDpr+DU3tok=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: kube-system

