---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '9.19.1'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
      interval: 1m
  install:
    remediation:
      retries: -1
  uninstall:
    timeout: 5m
    disableHooks: false
    keepHistory: false
  upgrade:
    remediation:
      retries: 5
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  values:
    additionalArguments:
      - --providers.file.filename=/config/traefik-config.yaml
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=jonnobrow.co.uk
      - --entrypoints.websecure.http.tls.domains[0].sans=*.jonnobrow.co.uk
      - --entrypoints.websecure.http.tls.domains[1].main=local.jonnobrow.co.uk
      - --entrypoints.websecure.http.tls.domains[1].sans=*.local.jonnobrow.co.uk
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=acme@jonnobrow.co.uk
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
      - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
      - --log.level=DEBUG
    ports:
      web:
        redirectTo: websecure
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-credentials
            key: email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-credentials
            key: apiKey
    ingressRoute:
      dashboard:
        enabled: false
    deployment:
      initContainers: 
        - name: volume-permissions
          image: busybox:1.31.1
          command: ["sh", "-c", "chown -Rv 65532:65532 /certs/* && chmod -Rv 600 /certs/*"]
          volumeMounts:
            - name: traefik-data
              mountPath: /certs
    persistence:
      enabled: true
      path: /certs
      size: 128Mi
      name: traefik-data
      accessMode: ReadWriteOnce
      storageClass: "local-storage"
    volumes:
      - mountPath: /config
        name: traefik-config
        type: configMap
