---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-data
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/traefik
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cappuccino
