---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: kube-system
spec:
  storageClassName: local-path
  volumeName: traefik-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
