apiVersion: v1
data:
  traefik-config.yaml: |+
    http:
      middlewares:
        headers-default:
          headers:
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            stsSeconds: 15552000
            customFrameOptionsValue: SAMEORIGIN
        nextcloud-redirect:
          replacePathRegex:
            regex: '^/.well-known/(card|cal)dav'
            replacement: '/remote.php/dav/'
        nextcloud-wellknown:
          replacePathRegex:
            regex: '^/.well-known/(.*)'
            replacement: '/index.php/.well-known/$1'
        nextcloud-bodysize:
          buffering:
            maxRequestBodyBytes: 4000000000

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: traefik-config
  namespace: kube-system
