apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.5.3
      sourceRef:
        name: jetstack
        kind: HelmRepository
        namespace: flux-system
  values:
    installCRDs: true
    image:
      registry: quay.io
      repository: jetstack/cert-manager-controller
      tag: v1.5.3
    webhook:
      image:
        registry: quay.io
        repository: jetstack/cert-manager-webhook
        tag: v1.5.3
    cainjector:
      image:
        registry: quay.io
        repository: jetstack/cert-manager-cainjector
        tag: v1.5.3
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "1.1.1.1"
      - "9.9.9.9"
