---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-api-token-secret.sops.yaml
  - helm-release.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
