apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secrets
  namespace: media-management
spec:
  encryptedData:
    values.yaml: AgCvKoiZRUJrXaZndk5JeW2eFUctIB2hIwzHBFbuAYhb2c5KnLKnkPisaqjsxKu/EWAlDcJlZCl7zETGx654PH0yZmNYElxq12mkcY61oU9lQXyn/HWJdwzTQ1y3DfqMi6mzGK2H53mhmoFeHnWbj5jAVUspkigW5KASTw7aysjZYx+l2A1jVtg5+AETQAQTVs3y4b1GEy7I/Cxqm08CRteSzNvVOoGK8EvNW5+XSFllgiZERcieQib+HVWJWqnPRsexAcsP9hukuYc3fUY9/arhEcjUpbKdCarH0q884TN+mryxfLTLstqQqVbcpot+OUReKM7QUFVW+6UwgvPRqfcIdukQDV6uqy6b2UXtKIzno6zjcAgYu71zujVax2VmbhzZU7gJA+byfiQ67KAMlkAFSUvWXKIeNrEgcNI9ksIeaP0EpPf5hEuV4gQVBHP/gtOMSu/M1ReXIXfWD7yVwGBdyjci1FEwSO0+BZ3tEoGRSibO8/1phm1WIarips26PhZ/lpT/vIMoldeB6NfwlfilaOOeIHcSVKZ1OSE2UvSJ9pFrP50unRZZektgxPwaie4IZO+ECSmPm99djcMGsmOfGBL6rvH0S4UA17VnbiVNJIF4if7tdelby7ltJzH7yF8y2sz91xTF+NxPoZVyRPNBTju9U8Cw8ww/8skWux2Uxh4gsj79hIBf1wIlJig3XtSjeRDIGYawrYZDFxw/cJhEpQiP2ftn9gv3pSfAZQinSI89yg81alWrOmwH9JU50VCUqzFlVdI750hDL8CUoz4TYIRr5qgMRAQxRLDb4Pk33yLFQfhJIKkVmOOXihSgvp8OAxNF5zBRoGxnbWKl2mm7UVcnl3/h6a8ha3O2g4cysAyjYx6RwnWp3ZLt6ftBNFCrhGXtRAfl+54jXHwQ2fE/o1n0JImCAUqhmJMoWbYsszKwaSzJgTdAAn+P9/egut+Pd9K3L7jHnYrLj2yVViAkY/MkO4i72Omxk6XReLb97U6RtB+JLz9tI3Fc9nqRk1xL6s6Kadtm2RO0o0KVzsXucSnWemzxEyRFJHt5aKFh/dAwzlUmDW0P6l+rtXyE1vDazMR36POVmeSbhOKqg194H9zDOW3oSvu+JNq+1mAcJCof+9QF9RUhW3Uh8xRgUVKAJl5C/PjLlZszZN5wbX0NM1v2GCFzL89kgxa5WiIw6rrGRcIU5xd5DumIqusJuRz+ELoqHk6qCXj0KHOWXjH24ddcHUleixOVE3BvvjfnWnFrvIIW9Rg0ts0MqQNodTflC/PCuI/CnGlhnus+OvDYLE2mJeClSe9pjPo4RO0K8r1JKBP48WNNm74Hs0pN05dxuK8H1MaqMidle40DdRxsbCEiVbMQtYuQKFueR5j9UjNHH+mYHGLTZk4u/pdNY6DQOLtnngFCf0C28BNUbFdRkTF6dd9329TJS7Q14Rh4zFZjzrqmvnWTw0gbuubuFADCJbI1yafNR7kfzoVkfpciQjDMZMjnK4SOu6Xw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: transmission-secrets
      namespace: media-management

