---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tranmission-downloads
spec:
  storageClassName: nfs
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/tmp-media/transmission
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranmission-downloads
  namespace: media-management
spec:
  storageClassName: nfs
  volumeName: tranmission-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
