apiVersion: v1
kind: PersistentVolume
metadata:
  name: music
spec:
  storageClassName: nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/music
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
spec:
  storageClassName: nfs
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/tv
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  storageClassName: nfs
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/movies
    server: 192.168.4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jbhdd/photos
    server: 192.168.4.2
