---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: home
spec:
  interval: 5m
  releaseName: firefly-iii
  chart:
    spec:
      # renovate: registryUrl=https://firefly-iii.github.io/kubernetes/
      chart: firefly-iii-stack
      version: 0.7.2
      sourceRef:
        name: firefly-iii
        namespace: flux-system
        kind: HelmRepository
  values:
    firefly-db:
      storage:
        existingClaim: firefly-iii-db-pvc
        class: nil
      configs:
        DBUSER: "${SECRET_FIREFLY_DB_USERNAME}"
        TZ: "Europe/London"
        PGPASSWORD: "${SECRET_FIREFLY_DB_PASSWORD}"
        POSTGRES_PASSWORD: "${SECRET_FIREFLY_DB_PASSWORD}"
        POSTGRES_USER: "${SECRET_FIREFLY_DB_USERNAME}"
        POSTGRES_DB: "firefly"
    importer:
      fireflyiii:
        url: "http://firefly-iii:80"
        vanityUrl: "https://firefly.${SECRET_DOMAIN}"
      config:
        env:
          TZ: "Europe/London"
    firefly-iii:
      image:
        repository: "fireflyiii/core"
        pullPolicy: IfNotPresent
        tag: version-6.1.1
      persistence:
        enabled: true
        existingClaim: firefly-iii-pvc
      config:
        env:
          DB_HOST: firefly-iii-firefly-db
          DB_USERNAME: "${SECRET_FIREFLY_DB_USERNAME}"
          SITE_OWNER: "${SECRET_FIREFLY_SITE_OWNER}"
      secrets:
        env:
          DB_PASSWORD: "${SECRET_FIREFLY_DB_PASSWORD}"
          APP_KEY: "${SECRET_FIREFLY_APP_KEY}"
      cronjob:
        enabled: true
        auth:
          token: "${SECRET_FIREFLY_CRON_TOKEN}"
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "lab.${SECRET_DOMAIN}"
        hosts:
          - "firefly.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "firefly.${SECRET_DOMAIN}"
