---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-db-volume
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/firefly-iii-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mocha
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-db-pvc
  namespace: home
spec:
  storageClassName: local-path
  volumeName: "firefly-iii-db-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-volume
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/firefly-iii
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mocha
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-pvc
  namespace: home
spec:
  storageClassName: local-path
  volumeName: "firefly-iii-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
