---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      version: 0.21.5
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent
      tag: "v1.23.2"
