---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- path: sops-config.yaml
  target:
    kind: Kustomization
    name: flux-system
    namespace: flux-system
