apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m
  url: https://github.com/rancher/local-path-provisioner
