# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ySK5z3AejTO8NMQTDIsy,iv:oNotVJWMMQsKg8kLkCEE+aU8pZXCQkFwrxw3o0ewzwA=,tag:jSjERIlPzPFJ3toOfgRm9g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GtePC97xp4979gjx7pRuqROOC4j4w5zx,iv:fgk9KCtS4lgRKUZt8Vcbrz6p3npxIZLTCcdtiwG/5wI=,tag:eO38QiZ++nnPUO97A5t6Xg==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:kAxa,iv:dUFeUVjJ5zufACHzQNM/w6tF90HzSuJwEXP5xEq9H3o=,tag:SfHP8wFnKWmeZr2IicCHWA==,type:str]
    SECRET_VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:L5Hm+0Y=,iv:6nlg8ElXyUtp7iUO2kHKDYRZ5Ew9j8XvDv87lCqrxrc=,tag:D/HE4STdqWOqDu/a6gmEkA==,type:str]
    SECRET_VPN_COUNTRY: ENC[AES256_GCM,data:xlSg51G/TnsQSPH/vQ4=,iv:Wh68prV+GV7/YMd9SLI8uXpwXuQ3WUABTNubmk3xcf8=,tag:AEcw19laaYoszg0dHKiDQw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Dqil4FiMCob5jne1WSVFpRFOD9xVel4T4paE4IpDnDGZuVmfiSe1xVXPSlFvXLDt,iv:jc4X5q8lBxtYGOFgfI0jSg8YIs46eugZIwOUV+qf8dY=,tag:EV9PHNl/y2isrxeVAz+wJQ==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:2ycCaStRI1y1Ybt65UqzhipepKSE4GZUfalt7PTdW8UwVlGq0nnUMwu+ONAh0OCb,iv:ADbBB6EIM3mULKKzcsKayu0VUB6Wg1FA6CWdgPuFbgU=,tag:Lvs63ljUB2cl4737NqLSlQ==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:uDTvaWEQVkWgBMR+SHTyhQ==,iv:m7HmJVUDwyGiCdTw89+MKbiaXNFvmfgrl/eyO2bGNJ4=,tag:vaSlaXqH5a/HZ0fwEgQvKw==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:VcDcD/NlQDm/7xqFRlGt/lvDrg==,iv:ShjkLIbQUopV1gvTS18Eu3sfL9FVK1YaZuwi/y9upNk=,tag:wttXaaQoHw5cXQJ10sBqcw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:jwSgHPPW2VA5PohD9nhRgDKGBufPETVgh3WerA==,iv:lUeXULdlYwmdBrgEkTg8+SsZUlxoh2OMO6h1i9S2vcY=,tag:o68Pus+vf9lqZkPYldI1Gg==,type:str]
    SECRET_MEALIE_EMAIL: ENC[AES256_GCM,data:9D9OS45FBhYgp5IOJT8LwhjU+8MXy+9A,iv:dxGW9zFdZfZx+wYtitvmQAoi3CeqXlEqERV9jrdmV4I=,tag:9CJgfEWI9DA0I0iuHCRqLQ==,type:str]
    SECRET_MEALIE_PASSWORD: ENC[AES256_GCM,data:I7zPREYenTegIy9FNZ7qbVpd4xoZfEE7+Z6WcY9N9QU=,iv:OgTpElZY2Ng7kSKe8g+iKki7TDeu5xQbxwe0dUmmhNw=,tag:2b8cWhyszZEBCdmnSjH7XA==,type:str]
    SECRET_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:Awlb0GfUnowf,iv:+0VRjPsiktiTerAKPsUjB1R3CxbEV0Qn8/IIo73nlD0=,tag:kR4MIhE5bUFBGJ3uBclW0Q==,type:str]
    SECRET_NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:e/SnAoRyPEeCw/8FHwCUpA==,iv:gd38XWS0uGt+rw1z9dFaVW2ogPnkPQ0NkyoaMtu4Ba0=,tag:0luPts+614Qx4+ph0jJsiQ==,type:str]
    SECRET_NEXTCLOUD_MAIL_FROM: ENC[AES256_GCM,data:IZ1VuRT4hiE=,iv:nVhU4B2RTVv651ICIlKoPwQcirZqPhSfRIQdK171/BA=,tag:ulB6gFR6lKzVuHKwXNPgtw==,type:str]
    SECRET_NEXTCLOUD_MAIL_PORT: ENC[AES256_GCM,data:/4tG,iv:56Q+OX9Aj10JR0tyV1hW8vTM/FGhD+oDP1uX1VYIdco=,tag:ErDwU0foQrQtIxFyU0SKUw==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Cp9mLGoZKfl3z0efE3nNwA==,iv:Vej5qz20b9Jc6+NdK1e0CUeu/m21egFUYoVnG88RwLk=,tag:4tIbalzx5YRriTg1KSL8Ng==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:rZVtyQFGXTivSgOb92JWjw==,iv:YpbpZk4hmXDZ8Ak40ACm0vPbNaFl1KSPr2o4+Lx0IMc=,tag:+cU22VBGVX4BzQSzecNvlQ==,type:str]
    SECRET_PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:tScydNAdveDxuk7kkq2gGAlw74DvCIhHXU9mUAK1vN7TDxJVXymaNs491z9/C/MM,iv:GT58OZTuX9MvagP9ntj6NF3NBW4Gtxlf9/Fble/2zwc=,tag:kiFTNHKONp1UHtbdSTGq2w==,type:str]
    SECRET_PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:J2SGVaP55PLZ,iv:hH1IsFeRPn36o6qZ+6WMbrvqt2md2LqlGhguvOyOW+o=,tag:diL5p7z3ibC98F8I27hRDg==,type:str]
    SECRET_PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:4JtKAaz7tbzrq8V9IpZgtHIb31C1d3l2,iv:CCn8hf4guQ0HHUpSY8MIhC+Komv2b1gzecLUxd9uxBQ=,tag:VFkRmnEzv3oC0nNIuUnoLQ==,type:str]
    SECRET_PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:E+/XtGNCiRxkW3xoDYDXx0LnyvM=,iv:2OXXAcKrznYSmnb9sAvg8Kjeq2i/JRvla9fRumZD0uc=,tag:xj/21VNeocnCkRCezvLUlA==,type:str]
    SECRET_PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:TkOGv9rzf9ZAzBUwQzATzhr8BUvRGfYYwJitgnAaxN8=,iv:dL0ykETR2faDOE17MvDk8p3V+PMwjlEKyVo/WrkAaLo=,tag:6g5J0WatbeCXA5hSLoAGKQ==,type:str]
    SECRET_GITEA_EMAIL: ENC[AES256_GCM,data:E88zdXzkhvlU4WuGgQr6kGJNLUWtoQXW,iv:NOc4eRfyeECguvaQovlRqA92JdE17BMicBvU972N6dE=,tag:oFuQe+kzsuW5mKnK6hffPA==,type:str]
    SECRET_GITEA_PASSWORD: ENC[AES256_GCM,data:Mq1yaAPOp8ZNXffgLbWkK3bAeL+uUqb0CSIaqgiCLeY=,iv:8Dhtu6OkkdCnETsya3DGAUfCBwuSLHZeYaLNrNkKYZE=,tag:bRrRFsVjWtj8ACsniD8WSA==,type:str]
    SECRET_GITEA_USERNAME: ENC[AES256_GCM,data:o62JWwGLLifZ,iv:dDJxYdtOffZCTuoJGiAPvQdsELzZ6OYPuxKynZZ6knU=,tag:dObH3JhVr5gdBt8kAjEiQQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:3yeHiYspurPSelyAlHKn/VIFfT40PKApMQDEzIdQmI8=,iv:RvKjuSxR7wIYumL+JdyCiYtKnbuW8Qk/bRiI2WEQ/hs=,tag:BFT1PHY5h3nDIAxwE94CCQ==,type:str]
    SECRET_RENOVATE_TOKEN: ENC[AES256_GCM,data:U4H8YFj+I7FkD4U4ZyFtwTKAkMjobPR7T4tCxhzcpXGYILe/ogzcSg==,iv:27qUyKuTkIIuUgwjIPPIyWjXXwm4U8cULl1hun3iqvE=,tag:n1sKxHzIGchPtYQght2Rew==,type:str]
    SECRET_DRONE_RPC_SECRET: ENC[AES256_GCM,data:jC+wK0dSVXGE2FC5Zyvi+eDLeM3qPycEXRU0soLLHvA=,iv:7yT8trNFvhQJWhD/uMhBqx1dzzhDod4PBMNe/rsEyFQ=,tag:/muUFPDO9QuSdcoRFh8Q+g==,type:str]
    SECRET_DRONE_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:NjUhn+ZcNd7zGT53LtbMIO84LeU=,iv:lI1WwKVCw+4JcLFj8soWCmUQqJ+wyOcyU5DYcViUPnE=,tag:f14BkoffnhGuTrj2NuC7lg==,type:str]
    SECRET_DRONE_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:BT8eEjraa6zCmwfJlkmPe/4aBQC6JRsPwggm65bBxQK13GQc++sTdA==,iv:eMxlPMLnB+6Ci81TIvKE+lTKTn7NEBHr245OpZKFtE4=,tag:rrZGJGEJI6VZm6lIW/FrEQ==,type:str]
    SECRET_TPLINK_USER: ENC[AES256_GCM,data:iLh7UmFGh+sC,iv:j3JXVbgOpaRVkiENSmyZd8t5pG8LW9vLrKrgso/e/us=,tag:oolCWTvf+CyqEBIYkeXfVw==,type:str]
    SECRET_TPLINK_PASS: ENC[AES256_GCM,data:t9Lz+dTVuY8fJg==,iv:FZnLvombN+bms5iKdaywGme2/9uutZerh1P8dhm6FgM=,tag:POph68N3fqdQNPsIHR+GkA==,type:str]
    SECRET_FIREFLY_SITE_OWNER: ENC[AES256_GCM,data:fN3py0AJqhqDelg2ySEMDRZ/KEmWjG1C,iv:7+wBnBroFRB2bIlXYsvyu4yFFrFnc2xtZJKNq+klC1Q=,tag:RfwuhfGzFW1fsYxudjwdyQ==,type:str]
    SECRET_FIREFLY_APP_KEY: ENC[AES256_GCM,data:jA3+tuXAmQpkCdzBh+08rwIUKE/jbHPpQ7w/uVQxNyo=,iv:G4OgpxxA9Y/MJS9+BDMTq9mPz3cBIDLfn/XaWarVG6E=,tag:5VjsfGs/iRsoBxSzrfaO1w==,type:str]
    SECRET_FIREFLY_DB_USERNAME: ENC[AES256_GCM,data:j/YUmv8mLCKl,iv:wrGTjs0hX510o2+yDBidx6Hla/9xyvsFYJuwZtea4Qo=,tag:NVigzNhA5/iaJgeATLhOhA==,type:str]
    SECRET_FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:o8W6BWNPH5jxBo0mC3EUb60YCVYrgjgDMqylCxZOI94=,iv:4r1HGFKBUm2XOZf2a6nHlUeoRJlILsBNJUMByhTIDSI=,tag:5SNBMqtzI6PE2AK6d6heqQ==,type:str]
    SECRET_FIREFLY_CRON_TOKEN: ENC[AES256_GCM,data:Wn2sUHRcDcxeHGNtn/gaaGyWOhNuIwslY5ovnCaBYUI=,iv:9LM8XuwZirE0huybNybVthynFHYnbTKfpTr+CoVZ8oc=,tag:d5XREVxZm9WcAG82o5A2Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-12T11:13:15Z"
    mac: ENC[AES256_GCM,data:kGqeI7hBTfWMjD8iuVjeCF2j5wwQr0VMAqbFl6lsDI/kzFRzjGxF/H3DTwHyRdVS2wKDUiCQlfB3F8bT0OqBfZI4hAA/KRN2AzuqZUJkGvf50+mpIUtbelpW39QsdIraHTdGIPpE+a2BWaCScQFuoj0PqviwFDBdb+iNxfx0M6E=,iv:frVDRg4n12LFQvPnqjGDgndcci74ipZMphxHuEeXb3k=,tag:OWbiah1usNe1dxoSIKtgmg==,type:str]
    pgp:
        - created_at: "2024-08-12T11:13:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzqujJzjVu3QAQ//YIuQtsxokHf5qQSIz2Y8STLvbQmwa1FoZtTB1UgePaO4
            yi0jk4q03J56HIq4IThI4FNDtEydQW7efZ/vgvPYsnWiYKVhtNSQMzbggiqBZRSL
            ZGpqREVZCE+0bH7bS0I7qUe2QcmDTguhl3MiRh4s9cxOQknSpiHy8a0vNFjlosvU
            C8eWVTwxwaKkZpZLe7m1Dz+ZXKXU7BH6Lc5O0pgtYU59CRWhGZTtdMk/KtHEeFuv
            UJPVVLTqKh8boEA5olfgfXfYicmzzO4jy+pQ82GSWu/n8ST6Ek0QU5KErTn9COi3
            ODFsFcajNS7XUtJQ8hou02OjKRG8+S5XGNrsBmRhw9HVh746SN19eqdLHgl6gnIZ
            B4hmIJfKqkMZ9wp3wkD4fq/YQI/A4cuZl7nxplyMx6kPNfwljm3T0ruFgshn1Sje
            pEnVzwHFGqLINfWeE9GwGD5EsJXPZ/VsqTaO9Ba4GjZZ5nnTuRDa9xrAwS9zdfly
            jmFRUvXiAyPJp8BAfMmufaXEKtbda+dreI2hWFEA4GHIm7dq5pv8vxribbeVrkpf
            l7S5YqX2vfJfCEgUayzOVz2J75rRbYbbdGDYqbRA2PY186X+epWVPS3UpZa9nwmG
            IjtugNaBZng15ffh26yx4U9RAOfOH+eoN8BEHWaLONzd8xXMRrxhmKTV3ACaV6rS
            XgH1E8KreL6rO9aXhqIxYvH+rp5mt4vzZgJPyUqJnaKciGRKm10bgDqwWBhRm27q
            c/iT2KRQRO0HOEy4LCnWJ3c/mCZ3V38AYxUSzHu3zRmCrtfQ2cDVg2P/ilh2O60=
            =UVKR
            -----END PGP MESSAGE-----
          fp: EEC9902152C0690384D8A104D86E27E8B691FAA1
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
